version: '3.7'

services:
  petclinic:
    build: ../../Desktop
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petClinic?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: my_strong_pass
    depends_on:
      - mysql
    networks:
      - petclinic
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: petClinic
      MYSQL_USER: admin
      MYSQL_PASSWORD: my_strong_pass
      MYSQL_ROOT_PASSWORD: my_strong_pass
    volumes:
      - petclinic_data:/var/lib/mysql
    networks:
      - petclinic
networks:
  petclinic:
volumes:
  petclinic_data: