spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  datasource:
    password: 'my_strong_pass'
    username: 'admin'
    url: jdbc:mysql://localhost:3306/petClinic?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    springframework:
      web: DEBUG
    javax:
      persistence: TRACE
